Feature/TRACTION-69, TRACTION-71, TRACTION-72
SFDO-Community/TractionThrive pull request #79
Opened 2020-04-21 10:11 UTC by rishabh-trac

# Critical Changes

# Changes
Created custom labels with translation supported for Hindi, Spanish, French languages
Updated the community and custom lightning and web components to include labels for multilingual support

# Issues Closed
TRACTION-69, 
TRACTION-71, 
TRACTION-72

2020-04-21 17:33 UTC, cwico requested changes
Thank you for doing this. I have some namespace injection issues in this PR for you to look at and and update. 

I know there are some hardcoded ids. Hope it works fine in the package. SFDC is weird.

2020-04-21 17:33 UTC, cwico commented on force-app/main/default/lwc/contactEditForm/contactEditForm.js
> +import STAFF_INFORMATION from '@salesforce/label/c.Staff_Information';
is this namespace safe?

2020-04-21 17:33 UTC, cwico commented on force-app/main/default/lwc/contactEditForm/contactEditForm.js
> +	labels = {
Super cool

2020-04-21 17:33 UTC, cwico commented on unpackaged/config/community/experiences/Traction_Thrive1/views/dashboard.json
> +          "componentName" : "c:overviewDashboard",
need %%%NAMESPACE_OR_C%%% for the cci script namespace injection

2020-04-21 17:33 UTC, cwico commented on unpackaged/config/community/experiences/Traction_Thrive1/views/home.json
> +      "componentName" : "c:contactCard",
need %%%NAMESPACE_OR_C%%% for the cci script namespace injection

2020-04-21 17:33 UTC, cwico commented on unpackaged/config/community/experiences/Traction_Thrive1/views/patients.json
> +          "componentName" : "c:patientTracker",
need %%%NAMESPACE_OR_C%%% for the cci script namespace injection

2020-04-21 17:33 UTC, cwico commented on unpackaged/config/community/experiences/Traction_Thrive1/views/supplies.json
> +          "componentName" : "c:allResources",
need %%%NAMESPACE_OR_C%%% for the cci script namespace injection

2020-04-22 17:09 UTC, rishabh-trac commented on force-app/main/default/lwc/contactEditForm/contactEditForm.js
> +import STAFF_INFORMATION from '@salesforce/label/c.Staff_Information';
yup it is

2020-04-22 17:51 UTC, cwico commented on unpackaged/config/community/experiences/Traction_Thrive1/views/customHome.json
> +      "componentName" : "%%%NAMESPACE_OR_C%%%:contactCard",
Yay!

2020-04-22 17:58 UTC, cwico approved these changes

2020-04-22 18:01 UTC, merged